### ISSUE TITLE
v14 - v16 - Product (short, long) description changes

### ISSUE THREAD

**Issue by hparfr** [shopinvader/odoo-shopinvader#1370]
**Objective**:  simplify UX and model design by moving fields out of shopinvader.product

## Today (<=14): 

short and description are on [shopinvader.product](https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader/models/shopinvader_product.py#LL24C1-L25C32)

## Future (14+, 16):

- short and description will be directly on product.template
- rename to description_sale_short, description_sale_long
- description_sale_long will be in html and description_sale_short in text

## Roadmap:

- [x] https://github.com/OCA/product-attribute/pull/1349/
- [ ]  module product_sale_description in v14
- [ ]  module shopinvader_product_sale_description in v16
- [ ]  module shopinvader_product_sale_description in v14

## shopinvader_product_sale_description in v14:

- add [meta fields](https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader/models/shopinvader_product.py#LL22C1-L23C34)
- add short, long description on category 
- change  [shopinvader.product](https://github.com/shopinvader/odoo-shopinvader/blob/14.0/shopinvader/models/shopinvader_product.py#LL24C1-L25C32) to be related fields
- create a basic migration script, support only one description and multi lang.

meta fields and description on categories are too e-commerce oriented to justify an oca module for them

In context of dedicated description for each backend, it should be implemented with module adding dedicated fields. 

For instance, if there is a b2c and a b2b shopinvader backends, products have differents description for each backend; then a new module should be developped changing the related field to a computed
