### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#317]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

* [x] base_url - By @rousseldenis - #318 
* [ ]  connector_generic
* [ ] connector_locomotivecms
* [ ]  partner_contact_company
* [ ]  product_media
* [ ]  product_online_category
* [ ]  product_rating
* [ ] product_stock_state
* [ ]  product_tag
* [x]  shopinvader - By @rousseldenis - #320 
* [x]  shopinvader_algolia
* [x] shopinvader_assortment - By @rousseldenis - #335 
* [x] shopinvader_backend_image_proxy
* [ ] shopinvader_contact_company
* [ ] shopinvader_custom_attribute
* [x] shopinvader_delivery_carrier
* [x] shopinvader_elasticsearch - By @rousseldenis - #331 
* [x] shopinvader_guest_mode - By @rousseldenis
* [x] shopinvader_image - By @rousseldenis - #334
* [ ] shopinvader_import_image
* [x]  shopinvader_lead - By @rousseldenis 
* [x]  shopinvader_locomotive - By @rousseldenis - #337 
* [ ]  shopinvader_locomotive_contact_company
* [x]  shopinvader_locomotive_guest_mode - By @rousseldenis - #338 
* [ ]  shopinvader_locomotive_rest_password
* [ ]  shopinvader_multi_categories
* [x]  shopinvader_partner_vat - By @rousseldenis - #339 l
* [ ] shopinvader_product_media
* [ ]  shopinvader_product_new
* [x] shopinvader_product_stock - By @rousseldenis - #332 
* [ ] shopinvader_product_stock_state
* [ ]  shopinvader_product_template_multi_link
* [ ]  shopinvader_promotion_rule
* [x] shopinvader_quotation - By @rousseldenis - #321 
* [ ]  shopinvader_sale_profile
* [x]  shopinvader_search_engine - By @rousseldenis - #329 
* [ ]  shopinvader_stripe
* [ ]  shopinvader_visible_discount

**Comment by rousseldenis** [comment]
cc @shopinvader I've just created this + 12.0 main branch

**Comment by rousseldenis** [comment]
@shopinvader Shouldn't 'base_url' module go to odoo-misc repository ?

**Comment by sebastienbeau** [comment]
Yes we can move it here

**Comment by sebastienbeau** [comment]
Regarding the migration it can be great if we can split the shopinvader is smaller module see here: : https://trello.com/c/uRTCjbuD/149-split-shopinvader-base-module-should-not-depend-on-sale
@bealdav maybe interested for helping on this point

**Comment by rousseldenis** [comment]
@sebastienbeau : I had a discussion with @lmignon and we let base_url in odoo-shopinvader for now as he wanted to keep 10.0 and 12.0 branches equals. But planning that after 12.0 migration

**Comment by sebastienbeau** [comment]
ok for me

**Comment by simahawk** [comment]
@sebastienbeau @rousseldenis time to update this list? :stuck_out_tongue_closed_eyes: 
Among the ones missing I've just found https://github.com/shopinvader/odoo-shopinvader/tree/10.0/shopinvader_product_template_multi_link
cross/up-selling is something we need. Do you have a plan / need for this?
What about the name? Shall we find a better one?

**Comment by lmignon** [comment]
@simahawk No need on our side for the moment. But the migration should be very easy.
Feels free to find a better name :smirk:

**Comment by simahawk** [comment]
@lmignon ok, thanks for the feedback :smirk: 
NOTE: `shopinvader_algolia` is migrated :wink:

**Comment by lmignon** [comment]
@simahawk Regarding shopinvader_product_template_multi_link, IMO we should improve the implementation. Indeed actually when you create a link from product a to product b, you must also create the reverse link between b and a...

**Comment by simahawk** [comment]
@lmignon I'm checking the implementation: now I get why it has been called like that. It depends on https://github.com/OCA/e-commerce/tree/10.0/product_template_multi_link which too me sounds over complicated. To me we could simply have m2m fields w/ their inverses. What do you think?

**Comment by lmignon** [comment]
I like the idea to be able to 'type' a link between two products.

Something like
```python
class ProductLinkType(models.Model):
    _name='product.link.type"

    name = fields.Char()
    inverse_name = fields.Char()


class ProductLink(models.Model):
    _name='product.link"

   product_tmpl_id_left = fiedls.Many2one()
   product_tmpl_id_right = fiedls.Many2one()  
   product_link_type = fields.Many2one()
   link_type_name = fields.Char(related="product_link_type.name") # left to right
   link_type_inverse_name = fields.Char(related="product_link_type.invese_name") # right to left


class ProductTemplate(models.Model):
    _inherit = "product.template"

    product_link_ids = fields.One2many(comodel_name="product.link")
        compute="_compute_product_link_ids",
    )


    @api.multi
    def _compute_product_link_ids(self):
        link_model = self.env["product.link"]
        domain = [
            "|",
            ("product_tmpl_id_left", "in", self.ids),
            ("product_tmpl_id_right", "in", self.ids),
        ]
        links = link_model.search(domain)
        links_by_product_id = defaultdict(link_model.browse)
        for link in links:
            links_by_product_id[link.product_tmpl_id_left.id] |= link
            links_by_product_id[link.product_tmpl_id_right.id] |= link
        for record in self:
            record.product_link_ids = links_by_product_id[
                record.id
            ]
```

With this kind of implementation:
* it become easy to export the links between products with the right semantic dependng of place of the product into the relation (left of right)
* when product a is linked to b, b is linked to a
* it's easy to display all the links for one product
* you are not restricted to to predefined link types
* ????

**Comment by simahawk** [comment]
Seems a good starting point :) Can you move this to a specific issue? Maybe straight on e-commerce repo.

**Comment by lmignon** [comment]
@simahawk here it is https://github.com/OCA/e-commerce/issues/307
