### ISSUE TITLE
Forward-port / Back-port TODO

### ISSUE THREAD

**Issue by lmignon** [shopinvader/odoo-shopinvader#416]
# Forward port from 10.0 to 12.0/13.0
* [x] ~~[10.0][ADD] Add a 'clear' on cart service + backend config #357 and [10.0][FIX] shopinvader: Don't override common test class #424~~
* [x] ~~[10.0][ADD] Add delivery service #325~~ by by @lmignon #479 
* [x] ~~[10.0][ADD] add module shopinvader_delivery_instruction #313 depends of https://github.com/OCA/sale-workflow/pull/757  -> done in #446~~ 
* [x] ~~[10.0][ADD] Add shopinvader_invoice #327~~ by @lmignon #481 
* [x] [10.0][FIX] shopinvader_promotion_rule: avoid to call the auto_apply rule twice after applying a coupon code #426 by @sebastienbeau #752 #753
* [x] ~~[10.0][FIX] shopinvader: prevent any creation of empty cart by search service #425~~
* [x] ~~[10.0][ADD] shopinvader_cart_expiry: add new feature to manage cart expiry delay #448~~ by @lmignon #482
* [x] ~~[10.0][IMP] shopinvader: Allows to download paid invoices for confirmed sal… #366~~ by @lmignon #483 
* [x] ~~[10.0][FIX] shopinvader guest mode export #465~~ by lmignon #484
* [x] ~~[10.0][FIX] shopinvader: change url_key of all bindings in case of product renaming #470~~ by @lmignon #485
* [x] ~~[10.0]FIX/Improve view of product.category/shopinvader.category #472~~ by @lmignon #486 
* [x] ~~[10.0] Merge shopinvader invoice + invoice download #407~~ by @lmignon #487
* [x] ~~[10.0][ADD] add delivery price simulation for cart #352~~ by @lmignon #488 
* [x] [10.0][FIX] shopinvader_promotion_rule fix promotions applied #562 by @sebastienbeau #756  #757
* [x] [10.0][ADD] Add module shopinvader_product_stock_assortment. #567 by @sebastienbeau  #754 #755
* [x] [10.0][ADD] shopinvader_delivery_carrier add sale info related to returned pickings #526 - By @sebastienbeau #685 #686
* [x] [10.0][UPD] shopinvader cart expiry: apply only on draft cart #535 - By @sebastienbeau #687 #688
* [x] [10.0][IMP][ADD] shopinvader - Document generate/download (pdf) #570 - By @sebastienbeau / @i-vyshnevska #769 #707
* [x] [10.0] add new addon to allow to display the category image if the product does not have one - #572 - by @sebastienbeau #699 #700
* [x] [10.0][UPD] Add the invoice/get service - #512 - by @sebastienbeau #701 #702
* [x] [10.0][FIX] Fix missing parameters into some search validator - #577 - By @HviorForgeFlow - #639 #644
* [x] [10.0][FIX] shopinvader: Shopinvader Manager inherits from queue manager #560 - By @HviorForgeFlow - #666 #673
* [x] [10.0] shopinvader.partner: switch to ondelete=restrict #563 - By @HviorForgeFlow - #649 
* [x] [10.0][ADD] Return also state label (not only technical value) - #404 - By @rousseldenis #638 
* [x] [10.0][FIX] fix database transaction error on multi-languages anonymous carts #595 - #694 #650 
* [x] [10.0][FIX] Fix shopinvader - Variants/Product active/inactive #568 - By @HviorForgeFlow - #656 #657 
* [x] [10.0][IMP] shopinvader_locomotive_reset_password: Add password expiration management #556 - By sebastienbeau #758  #759
* [ ] [10.0][UPD] shopinvader: force update pricelist and prices #449 - By @rousseldenis - #661 #679
* [ ] [13.0 ok] [10.0][UPD] update with shopinvader invoice payment #467 - By @sebastienbeau #770 
* [x] [10.0][FIX] shopinvader_sale_profile: Export default role if no profile #553  by @PierrickBrun #633 #760
* [ ] [13.0 ok] [10.0][CHG]shopinvader_invoice: add signed amount in response #584 - By @sebastienbeau  #810
* [ ] [10.0][CHG] being able to make the difference between an update done by the customer and update done internally in Odoo #596 - By @HviorForgeFlow #667
* [x] [10.0][IMP] shopinvader: Allow to copy a previous sale #558 - By @HviorForgeFlow - #655 #654 
* [ ] [10.0][IMP] shopinvader/guest_mode: Allows to update profile in guest mode #598 - By @sebastienbeau #819
* [x] [10.0] shopinvader: improve shopinvader.partner views #564 - By @rousseldenis - #691 #692 
* [x] [FIX] shopinvader: unique constrains on email should only apply to active records #620 - By @HviorForgeFlow  #675 #674
* [x] [10.0][FIX] fix issue when creating binding from the main record #607 NEEDS #340 - By @HviorForgeFlow #668 #669
* [x] 10.0 force technical user recompute export #622 - By @HviorForgeFlow - #677 #676 
* [x] [10.0][FIX] Fix delete synchronisation #360 - By @rousseldenis #643 #646
* [x] [10.0][FIX] action server in tree view must play on all selected records #458 - By @sebastienbeau  #761  @rousseldenis #694
* [x] [10.0][IMP] shopinvader_locomotive: Improve metadata #627 - By @sebastienbeau #762 #766 
* [x] [10.0][FIX] - shopinvader_delivery_carrier - flake8 fix #636 (not needed)
* [x] [10.0][FIX] shopinvader: sale service should return so linked to child partners #621 - #763 #707
* [x] [10.0][REF] refactor url generator #340 - By @HviorForgeFlow - #668 #669
* [ ] [13.0 ok] [10.0][ADD] Allow quotation download #653   #707 by  @i-vyshnevska 
* [ ] [10.0][ADD] Add shopinvader_sale_communication  #647   - By @sebastien  #820
* [x] [FIX] shopinvader_sale_profile: support profile without fiscal positions #651 - By @sebastienbeau #764 #765
* [ ] [IMP] add carrier code into api response #417 - By sebastienbeau #739 #821 
* [x] [10.0][FIX] fix incorrect api return #606 - By sebastienbeau #767 #771
* [ ] [FIX] API convention #634 - By sebastienbeau #822
* [ ] [13.0 ok] [IMP] add code in api for state and country in address #680 - By sebastienbeau #813 #814
* [ ] [10.0][IMP] shopinvader: Add validator for contact types #561 - By sebastienbeau #772 #773
* [ ] [ADD][10.0] add total without shipping and without discount in cart service response #793
* [ ] [10.0][IMP] shopinvader: Improve add item service #571   (perf improvement maybe not needed on V13+)
* [ ] [10.0][FIX] shopinvader: Recompute also sale order lines #599 (perf improvement maybe not needed on V13+)
* [ ] [10.0][FIX]shopinvader_sale_profile: fix wrong company for determining pricelists on partner #851
* [ ] [10.0][IMP] shopinvader_promotion_rule: let possibility to disable promotion rule by backend #724 
* [ ] [10.0][FIX] shopinvader_membership: missing ID in search - #905 
* [ ] [10.0][IMP] add a wizard for redirecting the product or the category manually - #682 
* [ ] [12.0][MIG][FW] shopinvader delivery instruction #446

# Backport from 12.0 to 10.0
* [ ] [12.0] [IMP]shopinvader_backend_view Improvements #411 AND [12.0][FIX] shopinvader_assortment backend_view #431
* [ ] [12.0] [IMP] Shopinvader_demo_app dependencies #410 + [12.0][IMP] shopinvader_demo_app: Add stripe #441
* [ ] [12.0] [IMP] locomotive easy config #428 + [12.0][FIX] shopinvader_locomotive: Provides the right url entrypoint for REST services #438 + [12.0][IMP] shopinvader_demo_app: uses localtest.me for elastic address #442
* [ ] [12.0] [IMP]shopinvader_locomotive: Exports new locales mapping to locomotive #434 
* [ ] [12.0] [FIX] shopinvader: Fix binding not created when a new lang is added #435 
* [ ] [12.0] [IMP] Compatible with new auth-api-key #420
* [ ] [12.0][FIX] shopinvader_demo_ap: Storage backend forced to public #436
* [ ] [12.0][FIX] shopinvader_elasticsearch: hierarchicalCategories into index must be nested #437 
* [ ] [12.0][IMP] add currencies to shopinvader's demo data #450
* [x] ~~[12.0][REF] clean shopinvader_quotation #397~~
* [ ] [12.0] [IMP] Shopinvader: allow the write on sale orders from partner without access #359 
* [ ] [12.0] Customer language + company_name handling #474
* [ ] [12.0][REF] Make search engine locomotive export settings generic #477
* [ ] [13.0][ENH] shopinvader: Easier product configuration access
* [ ] [13.0] Fix call to ir.config_parameter using sudo #704 

# Backport from 14.0
- [ ] [14.0][FIX] shopinvader: make the base_pricelist and base_pricelist.currency_id fields defined in the tests usable globally - #897 
- [ ] [ADD] 14.0 cancel and redraft sale endpoint https://github.com/shopinvader/odoo-shopinvader/pull/907

**Comment by acsonefho** [comment]
@lmignon I Forward port the clear cart #444 (I don't have rights to edit your document)

**Comment by acsonefho** [comment]
I also make this one #446 about module shopinvader_delivery_instruction

**Comment by simahawk** [comment]
to be addedd to FWD ports https://github.com/shopinvader/odoo-shopinvader/pull/465

**Comment by simahawk** [comment]
to be added to backports https://github.com/shopinvader/odoo-shopinvader/pull/359

**Comment by rousseldenis** [comment]
@lmignon Shouldn't we make a 13.0 section  too ?

**Comment by PierrickBrun** [comment]
to be added to backports:
#593 and #536 corresponding to #428 and #438 
#540 corresponding to shopinvader_partner_firstname
