### ISSUE TITLE
Misc improvements (aggregator)

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#452]
Aggregator of all the features we discussed at OCA days. I'll create one issue with the specs we wrote together per each of the following items:

- [x] Company validation #454 
- [x] Multiple users per same partner / company #454 
- [x] Protect "add to cart" from non-bound records #455
- [x] Sale wishlist https://github.com/shopinvader/odoo-shopinvader/issues/457
- [ ] Filter products by role / group [ref issue TODO]
- [ ] Filter products by customer / user  #709
- [ ] Products' visibility [ref issue TODO]
