### ISSUE TITLE
Migration to v13

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#539]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

* [x] base_url - By @lmignon - #478 
* [ ]  connector_generic
* [ ] connector_locomotivecms
* [ ]  partner_contact_company
* [ ]  product_media
* [ ]  product_online_category
* [ ]  product_rating
* [ ] product_stock_state - By @simahawk - https://github.com/OCA/product-attribute/pull/645
* [ ]  product_tag
* [x]  shopinvader - By @lmignon - #503 
* [x]  shopinvader_algolia - By @lmignon - #506 
* [x] shopinvader_assortment - By @lmignon - #507 
* [ ] shopinvader_backend_image_proxy
* [ ] shopinvader_contact_company
* [ ] shopinvader_custom_attribute
* [x] shopinvader_delivery_carrier - By @simahawk - #557 
* [x] shopinvader_elasticsearch - By @rousseldenis - #537 
* [x] shopinvader_guest_mode - By @HviorForgeFlow - #635 
* [x] shopinvader_image - By @lmignon - #509 
* [x] shopinvader_import_image - By @simahawk - #554 
* [x]  shopinvader_lead - By @gurneyalex - #582 
* [x]  shopinvader_locomotive - By @lmignon - #508 
* [ ]  shopinvader_locomotive_contact_company
* [x]  shopinvader_locomotive_guest_mode - By @HviorForgeFlow - #635 
* [ ]  shopinvader_locomotive_rest_password
* [ ]  shopinvader_multi_categories
* [ ]  shopinvader_partner_vat
* [ ] shopinvader_product_media
* [ ]  shopinvader_product_new
* [ ] shopinvader_product_stock - By @simahawk - https://github.com/shopinvader/odoo-shopinvader/pull/710
* [ ] shopinvader_product_stock_state - By @simahawk - https://github.com/shopinvader/odoo-shopinvader/pull/710
* [ ]  shopinvader_product_template_multi_link - By @simahawk - https://github.com/shopinvader/odoo-shopinvader/pull/708
* [x] shopinvader_product_variant_selector - By @simahawk - #551 
* [ ]  shopinvader_promotion_rule
* [ ] shopinvader_quotation
* [ ]  shopinvader_sale_profile
* [x]  shopinvader_search_engine - By @lmignon - #506 
* [ ]  shopinvader_visible_discount
