### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by rvalyi** [shopinvader/odoo-shopinvader#60]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] base_url
- [ ] connector_generic
- [ ] connector_locomotivecms
- [ ] partner_contact_company
- [ ] product_media
- [ ] product_online_category
- [ ] product_rating
- [ ] product_stock_state
- [ ] product_tag
- [ ] shopinvader
- [ ] shopinvader_algolia
- [ ] shopinvader_claim
- [ ] shopinvader_google_shopping
- [ ] shopinvader_lead
- [ ] shopinvader_m2mcategories
- [ ] shopinvader_mailjet
- [ ] shopinvader_paypal
- [ ] shopinvader_price_per_qty
- [ ] shopinvader_product_link
- [ ] shopinvader_product_media
- [ ] shopinvader_product_rating
- [ ] shopinvader_product_tag
- [ ] shopinvader_search_engine
- [ ] shopinvader_stripe
- [ ] shopinvader_visible_discount

**Comment by JayVora-SerpentCS** [comment]
partner_contact_company #162
