### ISSUE TITLE
Migration to v14

### ISSUE THREAD

**Issue by rousseldenis** [shopinvader/odoo-shopinvader#926]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

* [x] base_url
* [ ]  connector_generic
* [ ] connector_locomotivecms
* [ ]  partner_contact_company
* [ ]  product_media
* [ ]  product_online_category
* [ ]  product_rating
* [ ] product_stock_state
* [ ]  product_tag
* [x]  shopinvader
* [ ]  shopinvader_algolia - By @PierrickBrun - #856 
* [ ] shopinvader_assortment - By @chafique-delli - #863 
* [ ] shopinvader_backend_image_proxy
* [ ] shopinvader_cart_expiry - By @chafique-delli - #862 
* [ ] shopinvader_category_image_for_product - By @rousseldenis - #1085
* [ ] shopinvader_contact_company
* [ ] shopinvader_custom_attribute
* [x] shopinvader_customer_multi_user - By @chafique-delli - #864 
* [ ] shopinvader_customer_price - By @chafique-delli - #895 
* [ ] shopinvader_delivery_carrier - By @PierrickBrun - #858 
* [ ] shopinvader_elasticsearch - By @PierrickBrun - #917 
* [ ] shopinvader_guest_mod
* [ ] shopinvader_image - By @PierrickBrun - #857 
* [ ] shopinvader_import_image - By @hparfr - #871 
* [x] shopinvader_invoice - By @david-popa - #881 
* [ ]  shopinvader_lead
* [ ]  shopinvader_locomotive - By @PierrickBrun - #859 
* [ ]  shopinvader_locomotive_contact_company
* [ ]  shopinvader_locomotive_guest_mode
* [ ]  shopinvader_locomotive_rest_password
* [ ] shopinvader_locomotive_sale_profile - By @chafique-delli - #868 
* [ ] shopinvader_locomotive_wishlist - By @chafique-delli - #869 
* [x]  shopinvader_multi_category
* [ ] shopinvader_notification_default - By @chafique-delli - #893 
* [ ]  shopinvader_partner_vat
* [ ] shopinvader_pending_cart_reminder - By @acsonefho - #1045 
* [ ] shopinvader_product_media - By @PierrickBrun - #861 
* [ ]  shopinvader_product_new
* [ ] shopinvader_product_stock
* [ ] shopinvader_product_stock_state - By @PierrickBrun - #860 
* [ ]  shopinvader_product_template_multi_link
* [ ] shopinvader_product_variant_selector - By @chafique-delli - #865 
* [ ]  shopinvader_promotion_rule
* [ ] shopinvader_quotation
* [ ]  shopinvader_sale_profile
* [ ] shopinvader_sale_packaging_wishlist - By @chafique-delli - #903 
* [x]  shopinvader_search_engine - By @PierrickBrun - #855 
* [ ]  shopinvader_visible_discount
* [ ] shopinvader_wishlist - By @chafique-delli - #867
